[env."DATABASE_URL"]
relative = false
force = true
value = "sqlite:////home/chris/projects/chat/chat.db"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[build]
rustflags = ["-Clink-arg=-fuse-ld=mold", "-Zthreads=8"]
target = ["x86_64-unknown-linux-gnu"]
